# -*- coding: utf-8 -*-
"""src_utils_guardrails.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r5NQGSvwgkRNURwWXre1bpVupDK5cR26
"""

import re
import json
import logging
from pathlib import Path
from typing import List, Dict, Tuple
from datetime import datetime

try:
    import yaml
    CONFIG_PATH = Path(__file__).parent.parent / "config" / "security.yaml"
    with open(CONFIG_PATH, encoding="utf-8") as f:
        CONFIG = yaml.safe_load(f)
except Exception as e:
    logging.warning(f"Failed to load security.yaml: {e}")
    CONFIG = {
        "guardrails": {
            "enabled": True,
            "jailbreak_keywords": [],
            "dangerous_tools": [],
            "output_filters": [],
            "limits": {"max_output_tokens": 800, "timeout_per_step": 12}
        },
        "logging": {"enabled": True, "log_file": "logs/security_events.jsonl"}
    }

def is_jailbreak_attempt(message: str) -> Tuple[bool, str]:
    if not CONFIG["guardrails"]["enabled"]:
        return False, ""
    for kw in CONFIG["guardrails"]["jailbreak_keywords"]:
        if kw.lower() in message.lower():
            return True, f"Keyword match: '{kw}'"
    paradox_keywords = ["одновременно", "игнорируй правило", "не используй цифры", "ровно"]
    if any(kw in message for kw in paradox_keywords) and len(message.split()) > 30:
        return True, "Paradoxical instruction detected"
    return False, ""

def is_dangerous_content(message: str) -> Tuple[bool, str]:
    for tool in CONFIG["guardrails"]["dangerous_tools"]:
        if tool.lower() in message.lower():
            return True, f"Dangerous tool: '{tool}'"
    return False, ""

def validate_input(messages: List[Dict[str, str]]) -> Dict:
    if not messages:
        return {"allowed": True, "reason": "no messages", "severity": "low"}
    last_msg = messages[-1].get("content", "").strip()
    is_jailbreak, reason_jail = is_jailbreak_attempt(last_msg)
    is_dangerous, reason_dang = is_dangerous_content(last_msg)
    if is_jailbreak:
        log_security_event(
            event_type="jailbreak_attempt",
            message=last_msg,
            severity="high",
            details={"match": reason_jail}
        )
        return {
            "allowed": False,
            "reason": f"Jailbreak attempt blocked: {reason_jail}",
            "blocked_message": last_msg,
            "severity": "high"
        }
    if is_dangerous:
        log_security_event(
            event_type="dangerous_content",
            message=last_msg,
            severity="medium",
            details={"match": reason_dang}
        )
        return {
            "allowed": False,
            "reason": f"Dangerous content blocked: {reason_dang}",
            "blocked_message": last_msg,
            "severity": "medium"
        }
    total_chars = sum(len(m.get("content", "")) for m in messages)
    if total_chars > 5000:
        log_security_event(
            event_type="dos_attempt",
            message=f"{len(messages)} messages, {total_chars} chars",
            severity="medium"
        )
        return {
            "allowed": False,
            "reason": "Input too long (potential DoS)",
            "severity": "medium"
        }
    return {"allowed": True, "reason": "valid", "severity": "low"}

def log_security_event(**kwargs):
    if not CONFIG["logging"]["enabled"]:
        return
    log_path = Path(CONFIG["logging"]["log_file"])
    log_path.parent.mkdir(parents=True, exist_ok=True)
    record = {
        "timestamp": datetime.now().isoformat(),
        "event_id": hash(json.dumps(kwargs, sort_keys=True, ensure_ascii=False)) % (10**9),
        **kwargs
    }
    with open(log_path, "a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")