# -*- coding: utf-8 -*-
"""src_utils_output_critic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r5NQGSvwgkRNURwWXre1bpVupDK5cR26
"""

import re
import json
from pathlib import Path
from typing import Dict, List, Tuple
from .guardrails import CONFIG, log_security_event

def is_code_in_text(text: str) -> Tuple[bool, str]:
    patterns = [
        (r"<script>.*?</script>", "XSS HTML"),
        (r"import\s+(os|subprocess|sys|socket|requests)", "Dangerous import"),
        (r"(exec|eval)\s*\(", "Code execution"),
        (r"curl\s+http|wget\s+http", "External fetch"),
        (r"bash\s+-c|sh\s+-c", "Shell command"),
        (r"responder|evilginx|ntlm|mitm", "APT tool name"),
    ]
    for pattern, desc in patterns:
        if re.search(pattern, text, re.IGNORECASE | re.DOTALL):
            return True, desc
    return False, ""

def is_json_injection(text: str) -> Tuple[bool, str]:
    clean = text.strip()
    if clean.startswith("[{") or '"pattern"' in clean:
        try:
            data = json.loads(clean)
            if isinstance(data, list) and len(data) > 0:
                first = data[0]
                if isinstance(first, dict) and "pattern" in first and "reason" in first:
                    return True, "JSON rule extraction attempt"
        except json.JSONDecodeError:
            pass
    return False, ""

def critique_output(report: str) -> Dict:
    issues = []
    actions = []
    has_code, code_desc = is_code_in_text(report)
    if has_code:
        issues.append(f"Code detected: {code_desc}")
        actions.append("block")
    has_json, json_desc = is_json_injection(report)
    if has_json:
        issues.append(f"JSON injection: {json_desc}")
        actions.append("block")
    for tool in CONFIG["guardrails"]["dangerous_tools"]:
        if tool.lower() in report.lower():
            issues.append(f"Dangerous term: '{tool}'")
            actions.append("redact")
    if len(report.split()) > CONFIG["guardrails"]["limits"]["max_output_tokens"] * 1.2:
        issues.append("Output too long")
        actions.append("redact")
    if "block" in actions:
        log_security_event(
            event_type="output_blocked",
            report_snippet=report[:200],
            issues=issues,
            severity="high"
        )
        return {
            "safe": False,
            "issues": issues,
            "action": "block",
            "redacted_report": ""
        }
    if "redact" in actions:
        redacted = report
        for tool in CONFIG["guardrails"]["dangerous_tools"]:
            redacted = re.sub(rf"\b{re.escape(tool)}\b", "[REDACTED]", redacted, flags=re.IGNORECASE)
        log_security_event(
            event_type="output_redacted",
            original_len=len(report),
            redacted_len=len(redacted),
            issues=issues,
            severity="medium"
        )
        return {
            "safe": True,
            "issues": issues,
            "action": "redact",
            "redacted_report": redacted
        }
    return {
        "safe": True,
        "issues": [],
        "action": "allow",
        "redacted_report": report
    }